# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
  gym(scheme: "dsd",
  export_method:"development",
 )
  pgyer(api_key: "fd80a246b9e9d4ce621a8d7e4670cfa5", user_key: "c2d154d36c6c81e5d383399eb620e984")
 end
end
